### DISCUSSION TITLE
Customizing the Swiper navigation icons

### DISCUSSION THREAD

**Discussion by alibey-10** [nolimits4web/swiper#4998] [Q&A]
I am trying to custom the arrow icons in the navigation module but the only way I could see, to achieve that is through using classes "swiper-button-next/prev". I couldn't do much with it like rendering custom arrows. am I correct?

**Comment by amoknira** [comment]
I did so,  don't know another way. And with !important tag ofc. If someone know another solution,  would be cool to see it.

**Reply by rizqykhairani123** [reply]
> I am trying to custom the arrow icons in the navigation module but the only way I could see, to achieve that is through using classes "swiper-button-next/prev". I couldn't do much with it like rendering custom arrows. am I correct?

.swiper-button-prev {
  background-image: url(/assets/icons/arrow-circle-left.svg) !important;
  background-repeat: no-repeat;
  background-size: 100% auto;
  background-position: center;
}

.swiper-button-next {
  background-image: url(/assets/icons/arrow-circle-right.svg) !important;
  background-repeat: no-repeat;
  background-size: 100% auto;
  background-position: center;
}

.swiper-button-next::after {
  display: none;
}

.swiper-button-prev::after {
  display: none;
}

**Reply by Excelsior2021** [reply]
@rizqykhairani123 thank you!

**Reply by oknim** [reply]
doesn't work for me...
![image](https://github.com/nolimits4web/swiper/assets/138590875/e0f76838-e36d-4a56-bb8a-5565cbf0af76)

**Reply by muamarzidan** [reply]
> doesn't work for me... ![image](https://private-user-images.githubusercontent.com/138590875/327588557-e0f76838-e36d-4a56-bb8a-5565cbf0af76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNzcyNzEsIm5iZiI6MTcyMjA3Njk3MSwicGF0aCI6Ii8xMzg1OTA4NzUvMzI3NTg4NTU3LWUwZjc2ODM4LWUzNmQtNGE1Ni1iYjhhLTU1NjVjYmYwYWY3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QxMDQyNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmU5OWEyNGVmZmQ0MmQ2M2I4NjdlNTI2YjAyY2MxMjUwMzc2MTFhYjFiYWVmMjhjY2MzYzIwOTY0YjU5ZGMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SZ2p3-8M6pSFWpgipM4zBIJmUYDorFSaFzmfcM8Kqfw)

use this bro

1) setup the container or etc to wrap the navigation
![image](https://github.com/user-attachments/assets/1e81ed18-0183-4ddc-83a1-e3c8573115ee)


2) then just set with css

.swiper-button-prev::after {
  background-image: url('src/assets/lefto.svg');
  background-repeat: no-repeat;
  width: 100px;
  height: 100px;
  color: #FFFFFF00;
}

.swiper-button-prev.swiper-button-disabled::after {
  background-image: url('src/assets/leftoDisabled.svg') !important;
  background-repeat: no-repeat !important;
  width: 100px !important;
  height: 100px !important;
  color: #FFFFFF00 !important;
}

**Comment by oluwatimilehinawoniyi** [comment]
Please, after this while, has anyone found a solution to this?
Is the icon provided by Swiper a font? svg? what format is it exactly?

**Reply by rizqykhairani123** [reply]
.swiper-button-prev {
  background-image: url(/assets/icons/arrow-circle-left.svg) !important;
  background-repeat: no-repeat;
  background-size: 100% auto;
  background-position: center;
}

.swiper-button-next {
  background-image: url(/assets/icons/arrow-circle-right.svg) !important;
  background-repeat: no-repeat;
  background-size: 100% auto;
  background-position: center;
}

.swiper-button-next::after {
  display: none;
}

.swiper-button-prev::after {
  display: none;
}

**Reply by SharakPL** [reply]
It's an encoded font:
```scss
@at-root {
  @font-face {
    font-family: 'swiper-icons';
    src: url('data:application/font-woff;charset=utf-8;base64, d09GRgABAAAAAAZgABAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABGRlRNAAAGRAAAABoAAAAci6qHkUdERUYAAAWgAAAAIwAAACQAYABXR1BPUwAABhQAAAAuAAAANuAY7+xHU1VCAAAFxAAAAFAAAABm2fPczU9TLzIAAAHcAAAASgAAAGBP9V5RY21hcAAAAkQAAACIAAABYt6F0cBjdnQgAAACzAAAAAQAAAAEABEBRGdhc3AAAAWYAAAACAAAAAj//wADZ2x5ZgAAAywAAADMAAAD2MHtryVoZWFkAAABbAAAADAAAAA2E2+eoWhoZWEAAAGcAAAAHwAAACQC9gDzaG10eAAAAigAAAAZAAAArgJkABFsb2NhAAAC0AAAAFoAAABaFQAUGG1heHAAAAG8AAAAHwAAACAAcABAbmFtZQAAA/gAAAE5AAACXvFdBwlwb3N0AAAFNAAAAGIAAACE5s74hXjaY2BkYGAAYpf5Hu/j+W2+MnAzMYDAzaX6QjD6/4//Bxj5GA8AuRwMYGkAPywL13jaY2BkYGA88P8Agx4j+/8fQDYfA1AEBWgDAIB2BOoAeNpjYGRgYNBh4GdgYgABEMnIABJzYNADCQAACWgAsQB42mNgYfzCOIGBlYGB0YcxjYGBwR1Kf2WQZGhhYGBiYGVmgAFGBiQQkOaawtDAoMBQxXjg/wEGPcYDDA4wNUA2CCgwsAAAO4EL6gAAeNpj2M0gyAACqxgGNWBkZ2D4/wMA+xkDdgAAAHjaY2BgYGaAYBkGRgYQiAHyGMF8FgYHIM3DwMHABGQrMOgyWDLEM1T9/w8UBfEMgLzE////P/5//f/V/xv+r4eaAAeMbAxwIUYmIMHEgKYAYjUcsDAwsLKxc3BycfPw8jEQA/gZBASFhEVExcQlJKWkZWTl5BUUlZRVVNXUNTQZBgMAAMR+E+gAEQFEAAAAKgAqACoANAA+AEgAUgBcAGYAcAB6AIQAjgCYAKIArAC2AMAAygDUAN4A6ADyAPwBBgEQARoBJAEuATgBQgFMAVYBYAFqAXQBfgGIAZIBnAGmAbIBzgHsAAB42u2NMQ6CUAyGW568x9AneYYgm4MJbhKFaExIOAVX8ApewSt4Bic4AfeAid3VOBixDxfPYEza5O+Xfi04YADggiUIULCuEJK8VhO4bSvpdnktHI5QCYtdi2sl8ZnXaHlqUrNKzdKcT8cjlq+rwZSvIVczNiezsfnP/uznmfPFBNODM2K7MTQ45YEAZqGP81AmGGcF3iPqOop0r1SPTaTbVkfUe4HXj97wYE+yNwWYxwWu4v1ugWHgo3S1XdZEVqWM7ET0cfnLGxWfkgR42o2PvWrDMBSFj/IHLaF0zKjRgdiVMwScNRAoWUoH78Y2icB/yIY09An6AH2Bdu/UB+yxopYshQiEvnvu0dURgDt8QeC8PDw7Fpji3fEA4z/PEJ6YOB5hKh4dj3EvXhxPqH/SKUY3rJ7srZ4FZnh1PMAtPhwP6fl2PMJMPDgeQ4rY8YT6Gzao0eAEA409DuggmTnFnOcSCiEiLMgxCiTI6Cq5DZUd3Qmp10vO0LaLTd2cjN4fOumlc7lUYbSQcZFkutRG7g6JKZKy0RmdLY680CDnEJ+UMkpFFe1RN7nxdVpXrC4aTtnaurOnYercZg2YVmLN/d/gczfEimrE/fs/bOuq29Zmn8tloORaXgZgGa78yO9/cnXm2BpaGvq25Dv9S4E9+5SIc9PqupJKhYFSSl47+Qcr1mYNAAAAeNptw0cKwkAAAMDZJA8Q7OUJvkLsPfZ6zFVERPy8qHh2YER+3i/BP83vIBLLySsoKimrqKqpa2hp6+jq6RsYGhmbmJqZSy0sraxtbO3sHRydnEMU4uR6yx7JJXveP7WrDycAAAAAAAH//wACeNpjYGRgYOABYhkgZgJCZgZNBkYGLQZtIJsFLMYAAAw3ALgAeNolizEKgDAQBCchRbC2sFER0YD6qVQiBCv/H9ezGI6Z5XBAw8CBK/m5iQQVauVbXLnOrMZv2oLdKFa8Pjuru2hJzGabmOSLzNMzvutpB3N42mNgZGBg4GKQYzBhYMxJLMlj4GBgAYow/P/PAJJhLM6sSoWKfWCAAwDAjgbRAAB42mNgYGBkAIIbCZo5IPrmUn0hGA0AO8EFTQAA')
      format('woff');
    font-weight: 400;
    font-style: normal;
  }
}
```
It's in **node_modules/swiper/swiper.scss**. Not much you can do about it afaik.
But you still can change the font and use different characters:
```css
.swiper-button-prev::after, .swiper-button-next::after {
    font-family: "Open Symbol" !important;
}
.swiper-button-prev::after {  content: "\2190"; }
.swiper-button-prev::after {  content: "\2192"; }

// you may need to adjust the container size to match new icons
:root {
    --swiper-navigation-size: 40px !important;
}
.swiper-button-prev, .swiper-button-next {
    width: calc(var(--swiper-navigation-size) * 0.75); // if the aspect ratio of the new icon is 3/4
}
```
