### DISCUSSION TITLE
Large empty space at the end of navbar slides

### DISCUSSION THREAD

**Discussion by basicfeatures** [nolimits4web/swiper#5273] [Q&A]
Hi!

Trying to set up a sliding navbar but get this trailing whitespace at the end of my slides. Any chance anybody can spot the culpit?

https://jsfiddle.net/ccccssssssss/t6fs8o4p/

```js
var list = new Swiper(".swiper");
```
```css
header {
  display: flex;
  gap: 15px;
  position: fixed;
  width: 100%;
}

.list {
  background: yellow;
  overflow: hidden;
}

.swiper-slide {
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 5px;
  margin: 5px;
  width: auto !important;
}
```
```html
<header>
  <div class="list">
    <div class="swiper">
      <div class="swiper-wrapper">
        <div class="swiper-slide">
          <a>Lorem</a>
        </div>
        <div class="swiper-slide">
          <a>Ipsum</a>
        </div>
        <div class="swiper-slide">
          <a>Dolor</a>
        </div>
        <div class="swiper-slide">
          <a>Sit</a>
        </div>
        <div class="swiper-slide">
          <a>Lorem</a>
        </div>
        <div class="swiper-slide">
          <a>Dolor</a>
        </div>
        <div class="swiper-slide">
          <a>Sit</a>
        </div>
        <div class="swiper-slide">
          <a>Lorem</a>
        </div>
        <div class="swiper-slide">
          <a>Ipsum</a>
        </div>
        <div class="swiper-slide">
          <a>Dolor</a>
        </div>
        <div class="swiper-slide">
          <a>Sit</a>
        </div>
        <div class="swiper-slide">
          <a>Lorem</a>
        </div>
        <div class="swiper-slide">
          <a>Ipsum</a>
        </div>
        <div class="swiper-slide">
          <a>Dolor</a>
        </div>
        <div class="swiper-slide">
          <a>Sit</a>
        </div>
      </div>
    </div>
  </div>
</header>
```

If it's due to my `width: auto !important;` - do I have any other options?

Thanks!
