### DISCUSSION TITLE
Swiper slide shadow

### DISCUSSION THREAD

**Discussion by anstapol** [nolimits4web/swiper#5620] [Q&A]
Hey guys, I've been trying to allow `.swiper-slide` content (a card inside) to have it's own box-shadow.

It only worked when I've added 
```css
.swiper {
   overflow: visible !important;
}
```

Is there any less destructive way of achieving the same?
