### DISCUSSION TITLE
How to implement a continuous, infinite autoplay slider

### DISCUSSION THREAD

**Discussion by xndyz** [nolimits4web/swiper#5773] [Q&A]
AFAIK there is no option for a continuous autoplay slider that moves without momentum and does not stop at any point (it's infinite, or looping). Is there a hack that makes this possible?

**Comment by aarcoraci** [comment]
You can in fact achieve this with some CSS magic. I found the following codepen:
https://codepen.io/udovichenko/pen/xpwvjB

Look at the css rule:
```css
.swiper-container-free-mode > .swiper-wrapper{
  transition-timing-function : linear;
}
```

I tried on my project and it worked

**Reply by Scott716** [reply]
@aarcoraci thank you!  After 3 hours of trying to smooth out a carousel in swiper.js I found your css declaration for transition-timing-function and it worked.

**Reply by PubliAlex** [reply]
It works if all your slides have the same width, if you have variable slider width, the speed between slide will change, so it's not a true continous infinite autoplay

**Reply by heretoshleigh** [reply]
Yes, I am trying to implement this with variable widths, and I have not been able to find a solution. If anyone knows how to do it, please let me know!

**Reply by PubliAlex** [reply]
@heretoshleigh use another library like keen slider, swiper is not able to handle continous autoplay yet.

**Reply by Nerdy-Mike** [reply]
hi @aarcoraci, is there any way to slow down the linear autoplay animation? thanks in advance

**Reply by Nerdy-Mike** [reply]
oh never mind, I found it :D https://stackoverflow.com/questions/43801782/swiper-continous-loop-without-pause-between-sliding

**Reply by lcandy2** [reply]
for anyone use the latest version (v11 for now), use the updated code below:
```css
.swiper-free-mode > .swiper-wrapper{
  transition-timing-function : linear !important;
}
```
