### DISCUSSION TITLE
Scrollbar dragClass doesnt work

### DISCUSSION THREAD

**Discussion by mihail727** [nolimits4web/swiper#6133] [Q&A]
i'm trying to put the scrollbar in a separate html element, where i'm trying to override the styles of both the scrollbar itself and the drag element...
```vue
	<Swiper
		:direction="'horizontal'"
		:slides-per-view="3"
		:centered-slides="false"
		:space-between="32"
		:grab-cursor="true"
		:mousewheel="true"
		:scrollbar="{
		draggable: true,
		el: '#scroll',
		horizontalClass: 'scroll',
		}"
		:auto-height="true"
		:modules="[Mousewheel, Virtual, Scrollbar]"
		virtual
		class="h-fit overflow-auto"
	>
		<SwiperSlide
			id="product-card"
			v-for="product in productList"
			:key="product.id"
			:virtual-index="product.id"
		>
			<ProductCard
				:product="product"
				@card-click="onCardClick(product)"
			/>
		</SwiperSlide>
	</Swiper>
```
I'm able to override horizontalClass styles, but dragClass doesn't work
```css
.scroll {
	background-color: green;
}
.scroll-drag {
	fill: red;
	color: red;
	background-color: red;
	min-height: 4px;
	min-width: 100px;
}
```
result:
![](https://i.imgur.com/p24Ka0C.png)
