### DISCUSSION TITLE
Text instead of slide indicator

### DISCUSSION THREAD

**Discussion by Tomioka-Giyuu** [nolimits4web/swiper#6408] [General]
I used swiper to create a nested slider (vertical slider in a horizontal slider), I am trying to write text instead of the slider page indicator. anyone here has any clue on how to pull that off?

**Comment by hajirasyafi** [comment]
please see https://swiperjs.com/swiper-api#pagination,
<img width="1054" alt="Jepretan Layar 2023-02-24 pukul 04 43 01" src="https://user-images.githubusercontent.com/46818416/221037032-60aec8ff-dcda-401f-b236-bc0f94e83cc5.png">

**Reply by VIPStephan** [reply]
If I wanted to use text from the respective slide itself, how would that be done? Like, in each slide there is an element that contains a title, and I wanted that title to show up in the pagination. I want to get that text dynamically, but how do we access the current slide’s content?

**Reply by hajirasyafi** [reply]
here the sandbox : https://codesandbox.io/p/devbox/swiper-custom-bullet-x65ff8

The simple way :

```tsx
"use client";
import { Swiper, SwiperSlide } from "swiper/react";
import { Pagination } from "swiper/modules";
import "swiper/css";

// dont import below
// import "swiper/css/pagination"


interface Blog {
  title: string;
  content: string;
}
const blogPost: Blog[] = [
  {
    title: "The lucky ant",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    title: "Party Night",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    title: "No Rule No Life",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
];

const SwiperExample = () => {
  return (
    <div className="">
      <Swiper
        modules={[Pagination]}
        pagination={{
          el: ".container-for-pagination",
          clickable: true,
          type: "bullets",
          renderBullet: (index, className) => {
            return `<button class="${className} swiper-pagination-custom-bullet">${blogPost[index].title}</button>`;
          },
        }}
      >
        {blogPost.map((value, index) => (
          <SwiperSlide
            key={`slide-${index}`}
            className=""
          >
            <div className="">Title : {value.title}</div>
            <div>{value.content}</div>
          </SwiperSlide>
        ))}
      </Swiper>
      {/* Define container for pagination */}
      <div className="container-for-pagination"></div>
    </div>
  );
};

export default SwiperExample;

```

styling for css
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

@media (prefers-color-scheme: dark) {
  :root {
    --foreground-rgb: 255, 255, 255;
    --background-start-rgb: 0, 0, 0;
    --background-end-rgb: 0, 0, 0;
  }
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
}

@layer components {
  .swiper-pagination-custom-bullet {
    @apply p-2 border rounded;
  }
  .swiper-pagination-custom-bullet-active {
    @apply bg-white/20;
  }
}


```
