### DISCUSSION TITLE
swiper doesnt work properly with nextjs + chakra-ui

### DISCUSSION THREAD

**Discussion by ahmadxgani** [nolimits4web/swiper#6464] [Q&A]
i try [demo](https://codesandbox.io/p/sandbox/p3ngmy?file=%2Fsrc%2FApp.jsx&selection=%5B%7B%22endColumn%22%3A25%2C%22endLineNumber%22%3A18%2C%22startColumn%22%3A25%2C%22startLineNumber%22%3A18%7D%5D) and implement it in my project, but the overflow x is out of range as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/73988956/222906702-f8b893da-0075-4e20-8e79-9ee9935c06ab.png)

swiper.css:
```css
.swiper {
  width: 100%;
  height: 100%;
}

.swiper-slide {
  text-align: center;
  font-size: 18px;
  background: transparent;

  /* Center slide text vertically */
  display: flex;
  justify-content: center;
  align-items: center;
}

.swiper-slide img {
  display: block;
  width: 100%;
  height: 100%;
  object-fit: cover;
}
```

the code:
```tsx
"use client";
import { Img, Button, Heading, HStack, Switch, Tab, Tabs, Text, useColorMode, VStack, Link, Box, Image, Divider, List, ListIcon, ListItem, Accordion, AccordionButton, AccordionIcon, AccordionItem, AccordionPanel } from "@chakra-ui/react";
import { CheckCircleIcon, MoonIcon, SunIcon } from "@chakra-ui/icons";
import { Swiper, SwiperSlide } from "swiper/react";

import "@fontsource/dm-mono/500.css";
import "@fontsource/lexend/500.css";

import "swiper/css";
import "swiper/css/pagination";
import "./swiper.css";
import { Pagination } from "swiper";

<Box h="sm" position={"relative"}>
  <Swiper
    slidesPerView={1}
    spaceBetween={30}
    grabCursor={true}
    pagination={{
      clickable: true,
      dynamicBullets: true,
    }}
    modules={[Pagination]}
    loop
  >
    <SwiperSlide>
      <Box bg="teal.500" p={3} rounded="md" shadow={"dark-lg"}>
        <Link href="https://git-scm.com/" display="flex" gap={2}>
          <Image display="inline-block" src="/icons/techNtools/git.svg" alt="Git" w={"24px"} />
          <span>Git</span>
        </Link>
        <Text>Version control system</Text>
      </Box>
    </SwiperSlide>
    <SwiperSlide>
      <Box bg="teal.500" p={3} rounded="md" shadow={"dark-lg"}>
        <Link href="https://git-scm.com/" display="flex" gap={2}>
          <Image display="inline-block" src="/icons/techNtools/git.svg" alt="Git" w={"24px"} />
          <span>Git</span>
        </Link>
        <Text>Version control system</Text>
      </Box>
    </SwiperSlide>
    <SwiperSlide>
      <Box bg="teal.500" p={3} rounded="md" shadow={"dark-lg"}>
        <Link href="https://git-scm.com/" display="flex" gap={2}>
          <Image display="inline-block" src="/icons/techNtools/git.svg" alt="Git" w={"24px"} />
          <span>Git</span>
        </Link>
        <Text>Version control system</Text>
      </Box>
    </SwiperSlide>
  </Swiper>
</Box>
```

i'm little confused, i don't know how to debug this problem, any help will be appreciated 🙏
