### DISCUSSION TITLE
Problem with cube effect: image has wrong dimensions

### DISCUSSION THREAD

**Discussion by stla** [nolimits4web/swiper#6838] [Q&A]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/stla/swipeR

### Bug description

Hello,

I did a web application with the R programming language. It worked fine with **swiper** v8.4.5. I've just upgraded to v10.0.4 and now I get an issue with the cube effect. I'm not able to reproduce it with ordinary images: the images in my web application are generated by R. I can only provide a reproducible example to a R user.

Here is the problem. I have a cube with four graphics. The first one is nice. When I go to the second one, its dimensions are wrong. The third graphic is nice. The fourth graphic also has wrong dimensions. But when I open the console, the app is resized and then the problematic images become correct:

![swipeRcube_cpressd_resized](https://github.com/nolimits4web/swiper/assets/4466543/f83b5cfc-3909-43c4-a4fc-ff3606c1cf9e)

Would you know what happens and how could I fix this issue?

I have this custom CSS:

```css
.swiper-slide {
  background-position: center;
  background-size: cover;
}

.swiper-slide img {
  display: block;
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.swiper {
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translateX(-50%) translateY(-50%);
}
```

Maybe this issue is framework-specific, sorry for that. But again, it worked fine with v8.4.5, so maybe you know what is the change that could cause this behavior.

### Swiper version

10.0.4

### Platform/Target and Browser Versions

Chrome, Edge

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR
