### ISSUE TITLE
Swiper doesn't take box-sizing into account

### ISSUE THREAD

**Issue by pyrokinetiq** [nolimits4web/Swiper#1062]
When calculating offsets for slides, Swiper should ignore padding when the element has a `box-sizing` value of `border-box`.

Currently if I have a box with:
```css
.swiper-slide {
    width: 300px;
    padding: 15px;
    box-sizing: border-box;
}
```

When sliding to slide 2, there is a negative offset of `-330px` which would usually be correct, however `box-sizing: border-box;` means the padding does not contribute to the total box width, the padding pushes inwards instead.

So given the aforementioned styles, the negative offset should be `-300px` per box. i.e. Swiper needs to ignore padding in calculating offsets on slides with `box-sizing: border-box;`
