### ISSUE TITLE
slidesPerGroup: auto

### ISSUE THREAD

**Issue by jesperveldhuizen** [nolimits4web/Swiper#1422]
Is there a way to implement an 'auto' option for the 'slidesPerGroup' option? I'm using this Swiper to create a newspaper view and we use the following structure:
- Slide 1 (width 100%)
- Slide 2 (width 50%)
- Slide 3 (width 50%)
- Slide 4 (width 50%)
- Slide 5 (width 50%)
- Slide 6 (width 100%)

So infact there are 4 views (slide 1, slide 2/3, slide 4/5, slide 6).

When I click the 'next' button from **slide 1** I go to **slide 2/3**. So far so good. When I click 'next' again I go to slide **3/4**... this is wrong as I want to go to slide **4/5**.

Is this possible? 

Set up:

``` javascript
var mySwiper = new Swiper ('.swiper-container',
{
  nextButton: '.swiper-button-next',
  prevButton: '.swiper-button-prev',
  slidesPerView: 'auto'
});
```

``` html
<div class="swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide"><img src="images/pages/page0001_i1.jpg" /></div>
        <div class="swiper-slide"><img src="images/pages/page0002_i1.jpg" /></div>
        <div class="swiper-slide"><img src="images/pages/page0003_i1.jpg" /></div>
        <div class="swiper-slide"><img src="images/pages/page0004_i1.jpg" /></div>
        <div class="swiper-slide"><img src="images/pages/page0005_i1.jpg" /></div>
        <div class="swiper-slide"><img src="images/pages/page0006_i1.jpg" /></div>            
    </div>
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
</div>
```

Custom css:

``` css
.swiper-container
{
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
}

.swiper-slide
{
    width: 50%;
}

.swiper-slide:nth-child(even)
{
    text-align: right;
}

.swiper-slide:nth-child(odd)
{
    text-align: left;
}

.swiper-slide:first-child,
.swiper-slide:last-child
{
    width: 100%;
    text-align: center; 
}

.swiper-slide img
{
    max-width: 100%;
    max-height: 100%;
}
```
