### ISSUE TITLE
Normalized progress when using centeredSlides:true

### ISSUE THREAD

**Issue by ericmoff** [nolimits4web/Swiper#1615]
Hi,

when using `watchSlidesProgress: true` and `centeredSlides: true` the value of `swiper.slides[].progress` into `onProgress` callback is always 'shifted' due to swiper logic, how can we obtain a normalized progress value? (eg. a value that is 0 when active slide is centered and slider is not swiping?)

To understand, we need it to implement a custom transform that translates slides also on y-axis when swiping on x-axis:

```javascript
              var mySwiper = new Swiper ('.swiper-container', {
                    slidesPerView: 'auto',
                    centeredSlides: true,                    
                    watchSlidesProgress: true,
                    onProgress: function(swiper, progress){
                        for (var i = 0; i < swiper.slides.length; i++){
                            var slide = swiper.slides[i];
                            var translateY;
                            progress = slide.progress;
                            if (progress > 0) {
                                translateY = progress * swiper.height/2;
                            }
                            else {
                                translateY = -progress * swiper.height/2;
                            }
                            $(slide).css({
                                transform: 'translate3d(' + 0 + 'px,' + translateY + 'px,0)'
                            });
                        }
                    },

                    onTouchStart: function(swiper){
                        for (var i = 0; i < swiper.slides.length; i++){
                            $(swiper.slides[i]).css({ transition: '' });
                        }
                    },

                    onSetTransition: function(swiper, speed) {
                        for (var i = 0; i < swiper.slides.length; i++){
                            $(swiper.slides[i]).css({ transition: speed + 'ms' });
                        }
                    }
                })
```
```css
           @media only screen and (min-width: 45em) {
                .swiper-slide {
                    width: 75%;
                }
            }

           @media only screen and (min-width: 75em) {
                .swiper-slide {
                    width: 50%;
                }
            }
```
The above code works well only when `centeredSlides` is `false`, when `true` as needed then the active slide is wrongly shifted to the bottom when is centered, additionally it will go up when swiping to left and then goes down but when using `prevButton` instead of touch/mouse to swipe then transform behave differently
