### ISSUE TITLE
v3.3.1 slideTo, when moving to higher index, shows an incorrect higher-indexed slide

### ISSUE THREAD

**Issue by machuga** [nolimits4web/Swiper#1722]
I have a list of certain slides that can be accessed via a menu.  When I use `slideTo`, for example, from index `0` to index `4`, the correct index is given when checking `slider.activeIndex` and the correct `id` shows up in the hashnav, but a slide of a higher index, like `6` is shown instead.  I have verified this by using console logs of `activeIndex` and then checking the DOM to see which item was currently on screen.

Additionally, the slide that is shown is not the one that is marked as `active` by class name.

When I move from a higher index to a lower one (ex. `4` to `1`) the behavior works as expected.

I'm assuming the CSS transform is not correctly calculating the offset when moving forward, but I'm not sure why it reliably works when moving backwards.

My configuration for the slider is:

```coffeescript
  direction: 'horizontal'
  slidesPerView: 1
  mousewheelControl: true
  keyboardControl: true
  nextButton: '.swiper-button-next'
  prevButton: '.swiper-button-prev'
  hashnav: true
  preloadImages: false
  lazyLoading: true
  lazyLoadingInPrevNext: true
  lazyLoadingInPrevNextAmount: 3
  lazyLoadingOnTransitionStart: true
```

and my CSS (Sass) is as such:

```scss
/* The container */
.presentation--slides {
  padding-left: 0;

  /* The slide itself */
  .presentation--slide {
    list-style: none;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    text-align: center;

    /* the slide content */
    img {
      position: absolute;
      top: 0; bottom: 0;
      left: 0; right: 0;
      margin: auto;
      max-width: 100%;
      max-height: 100%;
    }
  }
}
```
All images currently take up the full width, which is the width of the viewport, but it's not always guaranteed depending on aspect ratio.

This is reproducible on at least OS X with Chrome and iPad with Safari.

I am a bit stumped and am not having much success in working around it.  Any input would be greatly appreciated.
