### ISSUE TITLE
Swiper killing specificity, margin for instance

### ISSUE THREAD

**Issue by katerlouis** [nolimits4web/Swiper#1771]
```css
.swiper-container {
	margin: 0 auto;
}
```

kills my `.margin-top`-class on the swiper-container.
In my opinion it's not Swipers job to declare margin on top or bottom of the container. That should be up to the user. If it's not specified by plugin-user it's probably zero anyway. So I hardly suggest being more specific:

```css
.swiper-container {
	margin-left: auto;
	margin-right: auto;
}
```
