### ISSUE TITLE
Jquery mobile phonegap 100% width

### ISSUE THREAD

**Issue by thenibbana** [nolimits4web/Swiper#196]
Hey,

I'm having an issue where the width of the slider isn't 100%. the text input is hidden.(or if it is, it seems to be doing it incorrectly).

I have the width and height set to 100% and am using jquery mobile.
Any ideas on why this would be?
Thanks

css code is 

``` css
.swiper1 .swiper-slide{
width:100%;
height:100%;
}
.swiper-wrapper, .swiper-container {
height:auto ;
width: auto ;
}
 .pagination1 {
        text-align: center;
        margin-top: 5px;
    }
   .pagination1 .swiper-pagination-switch {
        display: inline-block;
        width: 10px;
        height: 10px;
        border-radius: 10px;
        background: #999;
        box-shadow: 0px 1px 2px #555 inset;
        margin: 0 3px;
        cursor: pointer;
    }
    .pagination1 .swiper-active-switch {
        background: #fff;
    }
```

![sdf](https://f.cloud.github.com/assets/1822685/598879/a87361b4-cc3b-11e2-8811-09874c9dd266.png)
