### ISSUE TITLE
Swiper can not trigger ?

### ISSUE THREAD

**Issue by Axiom-shuvo** [nolimits4web/Swiper#2032]
I recently work in a mobile device template and i write a mega-menu where i show some device image and price and for slider the device i use swiper with bootstrap dropdown menu. preview link below : 
[OK image](http://imgur.com/a/NDQyH)
But when i use mobile device the swiper can not working .
[mobile not woking image](http://imgur.com/a/tuugu)

If i hold phone as vertical and i turn phone horizontal the swiper js trigger and working . 
[after phone turn it working normally](http://imgur.com/a/4DLm0)

As defult the megamenu hide on margin-top:- and when button click it come to the write place.
here css i use : 
```css
.helio-megamenu { position: fixed !important; width: 100% !important; top: -400px; display: block; visibility: hidden; background: rgba(0, 0, 0, 0.8) !important; border-bottom: 1px solid #00a99d; -webkit-transition: all 0.3s linear; -moz-transition: all 0.3s linear; -o-transition: all 0.3s linear; transition: all 0.3s linear; }
.helio-megamenu .megamenu-container { margin: 0 10%; }
.helio-megamenu .device-details img { width: 120px; }
.helio-megamenu .device-details h3 { margin: 10px 0px; font-weight: 300; }
.helio-megamenu .device-details h3 a { font-size: inherit !important; }
.helio-megamenu .device-details .img-responsive { margin: 10px auto; }
.helio-megamenu .device-details .btn { margin: 10px auto; font-size: 0.9em; background: #00a99d; }
.helio-megamenu .device-details .btn:hover, .helio-megamenu .device-details .btn:focus { background: #328a7d; -webkit-transition: all 0.1s ease-in-out; -moz-transition: all 0.1s ease-in-out; -o-transition: all 0.1s ease-in-out; transition: all 0.1s ease-in-out; }
.open > .dropdown-menu { visibility: visible; top: 90px; }
```

js

```js
var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        slidesPerView: 4,
        paginationClickable: true,
        spaceBetween: 30,
        nextButton: '.swiper-button-next',
        prevButton: '.swiper-button-prev',
        breakpoints: {
            1500: {
                slidesPerView: 3,
                spaceBetween: 70
            },
            991: {
                slidesPerView: 2,
                spaceBetween: 30
            },
            768: {
                slidesPerView: 2,
                spaceBetween: 20
            },
            600: {
                slidesPerView: 1,
                spaceBetween: 10
            }
        }
    });


  $('li.dropdown.other-device-list a').on('click', function (event) {
    $(this).parent().toggleClass("open");
    mySwiper.setWrapperSize('true');

  });

  $('body').on('click', function (e) {
    if (!$('li.dropdown.other-device-lists').is(e.target) && $('li.dropdown.other-device-lists').has(e.target).length === 0 && $('.open').has(e.target).length === 0) {
        $('li.dropdown.other-device-lists').removeClass('open');
      }
  });
```
Please help me , how i manually trigger swiper or solve the problem ???????
