### ISSUE TITLE
MS Edge fails to render first hidden element (filter applied on slide element)

### ISSUE THREAD

**Issue by rmalveis** [nolimits4web/Swiper#2111]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: Windows 10, MS Edge 38+/.

### What you did
A Slider with very simple configuration: 
```javascript 
return new window.Swiper(elements.container, {
      nextButton: elements.nextButton,
      prevButton: elements.prevButton,
      watchSlidesVisibility: true,
      slidesPerView: 'auto'
    });
```
The image inside my '.swiper-slide' element with filter:
```css
 //scss
  .swiper-container .swiper-wrapper .swiper-slide {
    width: 135px;
    margin-right: 17px;
    cursor: pointer;

    @media screen and (max-width: $viewport-max-content-small-width) {
      margin-right: 5px;
    }

    img {
      display: block;
      max-width: 135px;
      transition: filter .3s ease-in-out;
      transition-property: filter;
      border: 2px $players-slider-photo-border-color solid;
      **filter: grayscale(100%)**;
    }
...
```
in a very simple markup (Dust Render Engine): 
```HTML
<li class="swiper-slide">
  <figure>
      <img src="{img}" alt="{name}"/>
       <figcaption>
           {name}
       </figcaption>
  </figure>
</li>
``` 
### Expected Behavior
Expect to render all slides.

### Actual Behavior
When I click in the arrow to navigate the first hidden slide is not rendered. Sometimes it is rendered partially (cropped).

As far as I could investigate, it is a problem with MS Edge repaint that fails when the element is moved and has a filter applied.

I can't find a way to force swiper to use a fallback and instead of using "translate3d" to use the "left" property and that's why I checked the enhancement option. I know using left to move the element is not the best solution for a lot of reasons, but in this case would be an option just to MS Edge and old browsers while the problem persists.
