### ISSUE TITLE
Wrong width until page is resized on Firefox

### ISSUE THREAD

**Issue by loriepisicchio** [nolimits4web/swiper#2218]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: Firefox 55.0.3 (64 bits) on MacOS Sierra 10.12.6 (16G29)

### What you did
We use Swiper to show a list of items. We observe a strange behavior on Firefox.

### Expected Behavior
On Chrome, it works fine : our swiper is shown with 3 elements.

### Actual Behavior
On Firefox, on page load, only one element is displayed and stretched on the whole page width. We need to resize the page to get the right layout. 
When inspecting the generated HTML, we can see that the style element on the swiper-slide divs containing width and margin is not set on first load, but is set after resize. 
Note that the elements of the slider are loaded asynchronously.

URL to reproduce : 
https://support-swiper-demo.dev.v3.aws.lead.fm
Login : leadformance
Pwd : password

Open it in Chrome or Firefox. After a while you should see "Nearest locations" section above "Our Events" section. We have created 3 stores located around Rostov-on-Don so that you should see locations based on your geolocation. Please let me know if you are located elsewhere so that I can create new locations working for you.

Screenshot on Firefox before resize (bug)
https://s3-eu-west-1.amazonaws.com/swiper-demo-screenshots/Capture+d%E2%80%99e%CC%81cran+2017-09-27+a%CC%80+08.38.26.png

Screenshot on Firefox after resize (expected result)
https://s3-eu-west-1.amazonaws.com/swiper-demo-screenshots/Capture+d%E2%80%99e%CC%81cran+2017-09-27+a%CC%80+08.39.37.png

**Comment by nolimits4web** [comment]
Can you show how do you initialize Swiper and what options do you use?

**Comment by loriepisicchio** [comment]
The slider is initialized like this : 
```
const $nearestStoresSlider = this.$el.find('[data-lf-nearest-stores-slider]');
swiperSlider($nearestStoresSlider, sliderOptions);
```

Here is the value of `sliderOptions`
```
radius: '%bridge_front_starter_kit.search.radius%'
options:
  pagination: '.swiper-pagination'
  simulateTouch: false
  paginationClickable: true
  slidesPerView: 3
  spaceBetween: 60
  breakpoints:
    1200:
      slidesPerView: 3
      spaceBetween: 30
    992:
      slidesPerView: 2
      spaceBetween: 30
    768:
      slidesPerView: 1
      spaceBetween: 30
```
