### ISSUE TITLE
Slide not centered then resized window on 

### ISSUE THREAD

**Issue by steve231293** [nolimits4web/swiper#2553]
I have some slides, they are same width, for Ex 300px, and centered slide with larger width. Ex, 400px
How can you make single slide item centered with loop mode. 

* Swiper Version: 4.2.0
* Platform/Target and Browser Versions: CHROME on macOS
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/steve231293/pen/JLMWBb

Please help you a hand, thanks a lot

**Comment by nolimits4web** [comment]
This is not supported, slides must have fixed static size, if you try to change some of sizes dynamically during slide change it won't work

**Comment by schester44** [comment]
Your best bet would be to make the .swiper-slide a fixed width of say 400px and then put the actual slide one level deeper. Then apply the width to the nested slide. 

The css might look something like:

```css

.swiper-slide {
  width: 400px;
  display: flex;
  justify-content: center;
  
  .my-nested-slide {
   width: 300px; 
 }
}

.swiper-slide-active {
  .my-nested-slide {
    width: 400px;
  }
}
```
