### ISSUE TITLE
Inactive item opacity 0?

### ISSUE THREAD

**Issue by nickelmichel** [nolimits4web/swiper#2891]
Hi all!

I'm not a full developer so i ask help here.
I would like to automatically switch to 0 opacity the slides that have been seen, so only the active one can be on opacity:1 !
Thanks !

**Comment by alejandroiglesias** [comment]
@nickelmichel add the following styles:
```css
.swiper-slide:not(.swiper-slide-active) {
  opacity: 0;
}
```
