### ISSUE TITLE
3D Cube Effect - top-half of shadow disappeared when I am dragging it

### ISSUE THREAD

**Issue by qiangbro** [nolimits4web/swiper#3069]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5
* Platform/Target and Browser Versions: CHROME
* Live Link or JSFiddle/Codepen or website with isssue:  http://idangero.us/swiper/demos/230-effect-cube.html

### What you did
drag from right to left

### Expected Behavior
shadow always showing

### Actual Behavior
top-half of shadow disappeared when I am dragging it
![云之家图片20190514180351](https://user-images.githubusercontent.com/4646469/57689804-d3023f80-7672-11e9-95b3-e388ca086e6f.png)
![云之家图片20190514180411](https://user-images.githubusercontent.com/4646469/57689812-d4cc0300-7672-11e9-9382-5de8aff8a0ae.png)
![云之家图片20190514180422](https://user-images.githubusercontent.com/4646469/57689813-d5fd3000-7672-11e9-9a0b-636a440bb072.png)

P.S. Remember, an issue is not the place to ask questions. You can use [Stack Overflow](http://stackoverflow.com/questions/tagged/swiper)
for that.

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by udidol** [comment]
+1 on this, this should be opened and address

**Comment by smbln** [comment]
Please fix it :)

**Comment by qiangbro** [comment]
过了一年多都没解决吗 bug缠身？

**Comment by vltansky** [comment]
Moving blur & shadow to `:before` element seems like fixing the issue in chrome. 
https://stackblitz.com/edit/swiper-demo-23-3d-cube-effect-cazhqo

```css
.swiper-cube-shadow {
  -webkit-filter: initial !important;
  filter: initial !important;
  background: none !important;
}

.swiper-cube-shadow:before {
  content: "";
  background: #000;
  position: absolute;
  left: 0;
  top: 0;
  bottom: 0;
  right: 0;
  -webkit-filter: blur(50px);
  filter: blur(50px);
}
```
