### ISSUE TITLE
Box-sizing: border-box and centeredSlides

### ISSUE THREAD

**Issue by evild70** [nolimits4web/Swiper#310]
Seems to be an issue with using:

``` css
* {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
```

and the **centeredSlides** option.

Adding the above CSS to the following demo examples will result in slides at the end not showing up:
- 15-centered-slides.html
- 16-visibility-api.html
