### ISSUE TITLE
box-sizing inheritance issue with Foundation 6.x

### ISSUE THREAD

**Issue by sashabeep** [nolimits4web/swiper#3252]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: ANY
* Platform/Target and Browser Versions: ANY
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/sashabeep/pen/VwwZYJo

### What you did
By default, Foundation framework always use
```css
html {
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    ...
}
```
and then
```css
*, ::after, ::before {
    box-sizing: inherit;
}
```
for any other elements with built-in float/flex based columns

### Expected Behavior
Columns within slides respects foundation grid.

### Actual Behavior
Misplaced columns within slides.

### That's uncool
There is no mentions about box-sizing:content-box on the site https://swiperjs.com/
I wasted more than 100 minutes to finally figure out why this behavior occurs. You must at least mention that. Or change it to border-box to prevent this issue in future releases.
