### ISSUE TITLE
swiper height === aspect ratio && slider direction === vertical 

### ISSUE THREAD

**Issue by Baggio89** [nolimits4web/swiper#3429]
Referring to this: [#2378](https://github.com/nolimits4web/Swiper/issues/2378)
You can create a vertical swiper without using a fixed height. For example:

```html
<div class="container">
  <div class="inner">
    <div class="swiper-container-vertical">
      <div class="swiper-wrapper">
          <div class="swiper-slide">Slide 1</div>
          <div class="swiper-slide">Slide 2</div>
          <div class="swiper-slide">Slide 3</div>
      </div>
      <div class="swiper-pagination-bullets"></div>
    </div>
  </div>
</div>
```

```css
.swiper-container-vertical{
  overflow: hidden;
  width: 100%;
  height: 100%;
}
.container {
   position: relative;
   width: 100%;
   padding-top: 56.25%; /* 16:9 Aspect Ratio */
}
.inner {
   position:  absolute;
   top: 0;
   left: 0;
   bottom: 0;
   right: 0;
}
```
```javascript
var swiper = new Swiper('.swiper-container-vertical', {
  direction: 'vertical',
  slidesPerView: 1,
  // watchSlidesVisibility: true,
  loop: true,
  autoplay: {
      delay: 3000,
      disableOnInteraction: false
  },
  pagination: {
    el: '.swiper-pagination-bullets',
    type: 'bullets',
    clickable: true,
  },
});
```
