### ISSUE TITLE
iOS 13 shows blue edges when touching prev/next buttons

### ISSUE THREAD

**Issue by mig-hub** [nolimits4web/swiper#3501]
Hello,

Since switching my iPhone to iOS 13, I have realized that now when clicking/touching the prev/next buttons, a blue edge appears until we click/touch something else. It is not really a library issue as I am sure there is an easy CSS fix for this. But I am sure you might want to implement this as a default at some point.

The problem is I can't seem to find how to avoid this. I thought this looked like selection but I disabled selection on prev/next buttons with the following code and it does not seem to work.

```scss
.swiper-button-prev, .swiper-button-next {
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
```
I have also tried to make selection color transparent as a desperate attempt, but it did not work.

I am clearly missing something unless it is a Safari iOS bug.

Do you have any idea how to avoid this by any chance?

Thank you,
Mig

**Comment by ahmadalfy** [comment]
This is probably due to the focus state. You can stop it by setting the outline to none

```css
.swiper-button-prev:focus,
.swiper-button-next:focus {
  outline: none;
}
```
