### ISSUE TITLE
Navigation buttons for slider in vertical direction

### ISSUE THREAD

**Issue by strarsis** [nolimits4web/swiper#3592]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

SASS for having navigation buttons at the top and bottom 
(and pointing up- and downwards) for a slider in vertical direction:
```scss
.swiper-container-vertical {
  .swiper-button-next,
  .swiper-button-prev {
    left: 50%;
    transform: rotate(90deg);
    transform-origin: left center;
  }

  .swiper-button-prev {
    top: 10px;
  }

  .swiper-button-next {
    top: auto;
    bottom: 10px;
  }
}
````

Hm, the transform rotation makes it a bit difficult to position. The arrows are slightly offset.
