### ISSUE TITLE
Doesn't stretch slides to 100% height

### ISSUE THREAD

**Issue by catamphetamine** [nolimits4web/swiper#3632]
Doesn't stretch slides to 100% height.
The fix is:

* Reset this CSS rule.
```css
.swiper-slide {
  height: 100%
}
```

via

```css
.swiper-slide {
  height: auto
}
```

* Stretch the slides via flexbox
```css
.swiper-wrapper {
  align-items: stretch
}
```
