### ISSUE TITLE
Swiper sometimes huge when used on server side rendering

### ISSUE THREAD

**Issue by RickvanHek** [nolimits4web/swiper#3923]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.5.
* Platform/Target and Browser Versions: Chrome, safari, edge etc (all modern browsers + mobile browsers).
* Live Link or JSFiddle/Codepen or website with isssue:
https://bouclesandwaves-p67ctnmpb.vercel.app

### What you did
I'm using REACT version of swiper. When you load the page it all works perfectly. This is how i coded it:
```` js
import React from 'react';
import SwiperCore, {Navigation, Pagination, A11y, Autoplay} from 'swiper';
import {Swiper, SwiperSlide} from "swiper/react";

import styles from './Slideshow.module.scss';

SwiperCore.use([Navigation, Pagination, A11y, Autoplay]);
const Slideshow = ({images = [], intervalMs = 1000}) => {
    return <div className={styles.slideshow}>
        <Swiper
            slidesPerView={1}
            navigation
            pagination={{clickable: true}}
            loop
            autoplay={{delay: intervalMs}}
        >
            {
                images.map(src => <SwiperSlide key={src}><img className={'banner-img'} src={src}
                                                              alt={'banner'}/></SwiperSlide>)
            }
        </Swiper>
    </div>;
};

export default Slideshow;
````

Now the bug only happens in a particular case. First of all I am using server-side rendering using https://vercel.com/. 
When you go to the login page: https://bouclesandwaves-p67ctnmpb.vercel.app/login
and login, you can use test account:
test@test.com
password: test

Then it redirects to the home page, then it is perfectly fine. Then you log out (press user icon in right upper corner -> log out) and then log in again with the credentials, then the images will be huge: 
![image](https://user-images.githubusercontent.com/11407553/98169773-2b736f80-1eed-11eb-983e-b3e409426b6a.png)

These are the extra styles I already put on the swiper:
``` css
.swiper-container {
  width: 100%;
  height: auto;
  max-height: 100%;
  .swiper-wrapper {
    align-items: center;
    img {
      width: 100%;
    }

    .swiper-slide {
      display: -webkit-box;
      display: -ms-flexbox;
      display: -webkit-flex;
      display: flex;
      -webkit-box-pack: center;
      -ms-flex-pack: center;
      -webkit-justify-content: center;
      justify-content: center;
      -webkit-box-align: center;
      -ms-flex-align: center;
      -webkit-align-items: center;
      align-items: center;
    }
  }
}
```

Note that when I run the project locally, then I dont have any issue, so I think it has to do something with the server-side rendering.

### Expected Behavior
That the width and hight is always consistent

### Actual Behavior
The width and height is only correct the first time its loaded, afterwards it is huge.
