### ISSUE TITLE
Bug: Demos with effects crash on pinch zoom (iOS)

### ISSUE THREAD

**Issue by ntziolis** [nolimits4web/swiper#4926]
As of right now any demo that includes effects like flip, cards etc. crashes on pinch zoom.

Reproduction:  
- open https://swiperjs.com/demos/250-effect-flip/core.html on iOS device 
- pinch zoom in, pinch zoom out
- either results in site crash or reload and then site crash

Environment:
- crashes on latest iOS tested on the following devices: iPhone 8 plus and iPhone 12s Mini
- does NOT crash on latest iOS with iPhone 11 Pro Plus
- on iPad some of the effects do not crash like cards

Note:
- We have tried the Demos without images just using colored divs with the same result so this is not caused by images as such, but the underlying hooks.
- also when removing the effect specific css there is no Crash on pinch zoom. Obviously then the effect did not work either

**Comment by nolimits4web** [comment]
For me sounds like some iOS/device specific issue, can't see anything like that on my iPhone 11:

https://user-images.githubusercontent.com/999588/132493557-7f7a34fe-f7f6-4c9c-b11d-1ee578eb4f73.mp4

**Comment by binoben** [comment]
i got the same problem in Safari and Chrome, iPhone 12 mini


https://user-images.githubusercontent.com/29728002/132499118-04089aa8-f384-4c09-92a5-bcee1ddfa8fb.mov

**Comment by binoben** [comment]
here also with the same swiperjs demo:

https://user-images.githubusercontent.com/29728002/132527653-8ab3ac67-c857-458d-a70d-ca88bb26e494.MP4

**Comment by ntziolis** [comment]
@nolimits4web Do you have any chance (access to an iphone 8, 10, or 12) to reproduce this?

I did a bit more digging:
- Until the css for the effect that is used is included the app does not crash
  - so it doesnt seem to be js related
- Hence I imported the core css
- And extracted the flip css from the package and included it manually in my css section 
   - This allowed me to comment certain pieces out to identify swhich part of the css causes the issues
- After bit of fiddeling I found that the below was significantly more stable (almost no crashes, vs crashes all the time when pinch zooming)
   - obviously this has the cost o the effect not working correctly anymore
   - but I was hoping this might give you an idea of the root cause

```css
.swiper-flip {
  overflow: visible;
}
.swiper-flip .swiper-slide {
  pointer-events: none;
  -webkit-backface-visibility: hidden;
          backface-visibility: hidden;
  z-index: 1;
}
.swiper-flip .swiper-slide .swiper-slide {
  pointer-events: none;
}
// .swiper-flip .swiper-slide-active,
// .swiper-flip .swiper-slide-active .swiper-slide-active {
//   pointer-events: auto;
// }
// .swiper-flip .swiper-slide-shadow-top,
// .swiper-flip .swiper-slide-shadow-bottom,
// .swiper-flip .swiper-slide-shadow-left,
// .swiper-flip .swiper-slide-shadow-right {
//   z-index: 0;
//   -webkit-backface-visibility: hidden;
//           backface-visibility: hidden;
// }
```
