### ISSUE TITLE
Swiper doesn't stop swiping at the end of the carousel on mobile resolutions under 768px

### ISSUE THREAD

**Issue by rafaelfpereira** [nolimits4web/Swiper#5079]
### Check that this is really a bug

- [x] I confirm

### Reproduction link

I don't have one, sorry.

### Bug description

Sorry if this is the wrong place to post this, I'm new to GitHub issues, and am not sure if this is really a bug or something I did wrong. However I have exhausted all my other options, so I come seeking help even if it's just telling me to bug off.

When I swipe to the end of my carousel, instead of stopping at the last item inside it, you can keep swiping infinitely. The website i'm working is a wordpress env with twig for templating.

My currently installed Swiper version is **6.5.8**.

**HTML**
```twig
<div class="clients__carousel-container">
  <div class="clients__carousel swiper-container">
    <div class="clients__carousel-wrapper swiper-wrapper">
      {% for logo in logos %}
        {% set logo_src = assets_directory ~ '/icons/clients/logo-'
          ~ logo.icon
          ~ '.svg'
        %}
        <div class="clients__carousel-slide swiper-slide">
          <img src="{{ logo_src }}"
            alt="{{ logo.name }}"
            loading="lazy"
            width="{{ logo.width }}"
            height="{{ logo.height }}" />
        </div>
      {% endfor %}
    </div>
  </div>

  <button class="swiper-button-prev carousel__arrow carousel__arrow--prev clients__arrow clients__arrow--prev clients__arrow--disabled"
    title="{{ function('pll__', 'Slide anterior') }}">

  </button>

  <button class="swiper-button-next carousel__arrow carousel__arrow--next clients__arrow clients__arrow--next clients__arrow--disabled"
    title="{{ function('pll__', 'Próximo slide') }}">

  </button>
</div>
```
**CSS**
```css
.clients {
  --carousel-arrow-offset: -21px;
  padding-top: 83px;
  padding-bottom: 79px;
}

.clients__container {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.clients__title {
  font-weight: 600;
  font-size: 56px;
  line-height: 61px;
}

.clients__carousel-container {
  width: 100%;
  margin-top: 67px;
  padding: 0 80px;
  position: relative;
}

.clients__carousel-wrapper {
  align-items: center;
}

.clients__carousel-slide {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 0 20px;
}

/* dark theme */
.clients--dark {
  background-color: var(--concrete);
}

.clients--dark .clients__title {
  color: var(--mine-shaft);
}

@media screen and (max-width: 1180px) {
  .clients {
    --carousel-arrow-offset: 0;
  }
}

@media screen and (max-width: 768px) {
  .clients {
    padding-top: 41px;
    padding-bottom: 22px;
  }

  .clients--dark {
    padding-bottom: 33px;
  }

  .clients__container {
    align-items: flex-start;
  }

  .clients__title {
    font-size: 24px;
    line-height: 29px;
    letter-spacing: 0.01em;
  }

  .clients__carousel {
    width: 100%;
    margin-top: 12px;
  }

  .clients__carousel-container {
    width: calc(100% + (var(--container-spacing) * 2));
    margin-top: 0;
    margin-left: calc(var(--container-spacing) * -1);
    padding: 0;
  }

  .clients__carousel-slide {
    width: auto;
    padding: 0;
    transform: translateX(var(--container-spacing)) !important;
  }

  .clients__carousel-slide:last-of-type {
    padding-right: var(--container-spacing);
  }

  .clients__arrow {
    display: none;
  }
}

@media screen and (max-width: 767px) {
  .clients__carousel-slide {
    margin-right: 30px;
  }
}

@media screen and (max-width: 414px) {
  .clients__carousel-slide {
    width: 30vw;
    margin-right: 20px;
  }
}
```
**JS**
```js
import Swiper, { Navigation } from 'swiper'

export default function setupClientsCarousel() {
  Swiper.use([Navigation])

  new Swiper('.clients__carousel', {
    slidesPerView: 'auto',
    spaceBetween: 20,
    preloadImages: false,
    grabCursor: true,
    navigation: {
      prevEl: '',
      nextEl: '',
    },
    breakpoints: {
      480: {
        slidesPerView: 2,
        spaceBetween: 0,
      },
      768: {
        slidesPerView: 4,
        spaceBetween: 0,
        navigation: {
          prevEl: '.clients__arrow--prev',
          nextEl: '.clients__arrow--next',
          disabledClass: 'carousel__arrow--disabled clients__arrow--disabled',
        },
      },
    },
  })
}
```

### Expected Behavior

I would like Swiper to stop at the end of the list of clients and bounce back to the end when trying to scroll past it.

### Actual Behavior

When I swipe to the end of my carousel, instead of stopping at the last item inside it, you can keep swiping infinitely.

### Swiper version

6.5.8

### Platform/Target and Browser Versions

Google Chrome, Android and iOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR
