### ISSUE TITLE
Swiper navigation on Ionic 7 not showing

### ISSUE THREAD

**Issue by allestaire** [nolimits4web/swiper#6797]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

adadad

### Bug description

No color showing on bullets

<img width="472" alt="Screen Shot 2023-07-01 at 10 30 06 AM" src="https://github.com/nolimits4web/swiper/assets/68372409/750ba624-7812-40c5-9b20-524638fc5d04">

Seems like the css variable not working
<img width="434" alt="Screen Shot 2023-07-01 at 10 30 51 AM" src="https://github.com/nolimits4web/swiper/assets/68372409/073a03ef-bd9f-4613-b583-cb4bd6163ef4">

### Swiper version

9.3.2

### Platform/Target and Browser Versions

12.2.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by allestaire** [comment]
Need to override on `variable.css`

```css
.swiper {
  --bullet-background-active: var(--ion-color-primary);
  --bullet-background: var(--ion-color-primary);
  --progress-bar-background: var(--ion-color-primary);
  --progress-bar-background-active: var(--ion-color-primary);
}

```
