### ISSUE TITLE
calculateHeight on a responsive swiper.

### ISSUE THREAD

**Issue by stuartcaney** [nolimits4web/Swiper#721]
Hi all,

I’m pretty new to coding so would very much appreciate any pointers to how I can fix a problem I’m having with the calculateHeight on a responsive swiper.

I have everything working how I would like, and it works if the browser is resized slowly, but if a device is rotated or browser snapped to full screen, it doesn’t seem to recalculate the height unless the browser is refreshed.

I’m not sure if the it’s way i’ve set the swiper up or if i need to do some sort of callback;

I have pasted my code below and there is a live example on a test server at http://viiiyears.co.uk/

Thank you in advance if you can help ,

Stuart

HTML

``` html
<section class="book-swiper">
    <div class="arrow-wrapper">
        <div class="arrow-left"><a class="icon-arrowL" role="button"></a></div>
        <div class="arrow-right"><a class="icon-arrowR" role="button"></a></div>
    </div>
    <div class="swiper-life">
        <div class="swiper-wrapper">

            <!--First Slide-->
            <div class="swiper-slide">
                <figure class="slide-img">
                    <img src="img/Wesley-Henry-webtest2.jpg" alt=""/> 
                </figure>
            </div>

            <!--Second Slide...-->
        </div>
    <div class="pagination"></div>
    </div>
</section><!-- END book-swiper-->
```

CSS

``` css

img {
    width: 100%;
    max-width: 100%;
    height: auto;
}
.swiper-life  {
    position: relative;
    display: block;
    width: 100%;
    overflow: hidden;
    margin:0 auto;
    backface-visibility: hidden; /*prefixed....*/
    z-index:1; }

.swiper-wrapper {
    position: relative;
    width:100%; 
/*transitions....*/
}

@media all and (min-width: 47em) {
.swiper-life {
    width: 46.875em; 
    margin-left:auto;
    margin-right:auto; }
}
@media all and (min-width: 110em) {
.swiper-life {
     width: 55em; }
}

/* Wrapper */
.book-swiper {
    position: relative;
    display: flex;
    margin: 0 auto;
    max-width: 58em;
    padding: .6rem 0 1.6rem 0; 
}
@media all and (min-width: 30em) {
.book-swiper {
    padding: 1.6rem 0; }
}
@media all and (min-width: 110em) {
.book-swiper {
     max-width: 70em; }
}
@media all and (min-width: 110em) {
.book-swiper {
    padding: 1.8rem 0; }
}

```

JS

``` js
//Life in Film Swiper
window.onload = function () {
    "use strict";
    var lifeSwiper = new Swiper('.swiper-life', {
            calculateHeight: true,
            resizeReInit: true,
            updateOnImagesReady: true,
            pagination: '.pagination',
            paginationClickable: true,
            grabCursor: true                 
        });
    //arrow clicks
    $('.icon-arrowL').on('click', function(e){
        e.preventDefault();
        lifeSwiper.swipePrev();
    });
    $('.icon-arrowR').on('click', function(e){
        e.preventDefault();
        lifeSwiper.swipeNext();
    });
};

```
