### ISSUE TITLE
After setting breakpoints and resizing the window multiple times, the page becomes very laggy.

### ISSUE THREAD

**Issue by cage1618** [nolimits4web/swiper#7752]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/k3cyyc?file=/src/App.jsx

### Bug description

as the title, bleow is my breakpoints:
```yaml
640:
  slidesPerView: 2
  slidesPerGroup: 2
  spaceBetween: 0

1024:
  slidesPerView: 4
  slidesPerGroup: 4
  spaceBetween: 0

1280:
  slidesPerView: 5
  slidesPerGroup: 5
  spaceBetween: 0

1440:
  slidesPerView: 6
  slidesPerGroup: 6
  spaceBetween: 0

1680:
  slidesPerView: 7
  slidesPerGroup: 7
  spaceBetween: 0

1920:
  slidesPerView: 8
  slidesPerGroup: 8
  spaceBetween: 0

2560:
  slidesPerView: 10
  slidesPerGroup: 10
  spaceBetween: 0

3440:
  slidesPerView: 14
  slidesPerGroup: 14
  spaceBetween: 0
```

### Expected Behavior

The page remains smooth.

### Swiper version

11.1.14

### Platform/Target and Browser Versions

macos safari 15.6.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR
